version: "3.3"
services:

  nginx:
      build:
        context: ./nginx
      ports:
        - "80:80"
      deploy:
        replicas: 1
      depends_on: 
        - "fluentd"
      volumes:
        - ./nginx:/usr/share/nginx/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      links:
        - "fluentd"
      logging:
        driver: "fluentd"
        options:
          fluentd-address: localhost:24224
          tag: httpd.access
      networks:
        - elk-nginx

  fluentd:
      build:
        context: ./fluentd
      ports:
        - "24224:24224"
        - "24224:24224/udp"
      depends_on: 
        - "elasticsearch"
      networks:
        - elk-nginx
      volumes:
        - ./fluentd/etc:/fluentd/etc

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.0"
    ports:
      - "9200:9200"
    expose:
      - 9200
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk-nginx
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"


  kibana:
    image : "docker.elastic.co/kibana/kibana:7.15.0"
    links:
      - "elasticsearch"
    environment:
      ELASTICSEARCH_HOST: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk-nginx

  

  



networks:
  elk-nginx:
    # driver: bridge

volumes:
  elasticsearch-volume: